name: Daily Trivia Update with WOW Facts & Daily Facts

on:
  schedule:
    # Run daily at 12:00 AM UTC
    - cron: '0 0 * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-trivia:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # Install SQLite (usually available by default)
        python -c "import sqlite3; print('SQLite version:', sqlite3.sqlite_version)"
        
    - name: Generate daily trivia with WOW facts and daily fact
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        GITHUB_USERNAME: ${{ github.repository_owner }}
        GITHUB_REPO: ${{ github.event.repository.name }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python src/core/daily_trivia.py
        
    - name: Process answers
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_USERNAME: ${{ github.repository_owner }}
        GITHUB_REPO: ${{ github.event.repository.name }}
      run: |
        python src/core/process_answers.py
        
    - name: Debug Leaderboard
      run: |
        echo "🔍 DEBUGGING LEADERBOARD DATA:"
        echo "================================"
        python -c "
        from src.core.database import TriviaDatabase
        from src.core.daily_trivia import get_top_leaderboard, load_leaderboard
        
        # Load leaderboard
        db = TriviaDatabase()
        leaderboard = db.get_leaderboard()
        print(f'📊 Total users in database: {len(leaderboard)}')
        print(f'👥 Users: {list(leaderboard.keys())}')
        
        # Get top 10 users
        top_users = get_top_leaderboard(leaderboard, max_entries=10)
        print(f'🏆 Top {len(top_users)} users:')
        for i, (username, stats) in enumerate(top_users, 1):
            print(f'  {i}. @{username}: {stats[\"total_points\"]} points, {stats[\"current_streak\"]} streak, {stats[\"total_correct\"]} correct')
        
        if not top_users:
            print('❌ No users found in leaderboard!')
        "
        echo "================================"
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git diff --quiet && git diff --staged --quiet || git commit -m "🤖 Daily update: Trivia + WOW facts + Daily fact + Database history - $(date +'%Y-%m-%d')"
        git push origin main 