name: Daily Trivia Update

on:
  schedule:
    # Run daily at 12:00 AM UTC
    - cron: '0 0 * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-trivia:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # Install SQLite (usually available by default)
        python -c "import sqlite3; print('SQLite version:', sqlite3.sqlite_version)"
        
    - name: Generate daily trivia and update fact
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        GITHUB_USERNAME: ${{ github.repository_owner }}
        GITHUB_REPO: ${{ github.event.repository.name }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TRIVIA_DB_PASSWORD: ${{ secrets.TRIVIA_DB_PASSWORD }}
      run: |
        python src/core/daily_trivia.py
        
    - name: Process answers
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_USERNAME: ${{ github.repository_owner }}
        GITHUB_REPO: ${{ github.event.repository.name }}
        TRIVIA_DB_PASSWORD: ${{ secrets.TRIVIA_DB_PASSWORD }}
      run: |
        python src/core/process_answers.py
        
    - name: Update README with latest leaderboard
      env:
        TRIVIA_DB_PASSWORD: ${{ secrets.TRIVIA_DB_PASSWORD }}
      run: |
        python -c "from src.core.daily_trivia import update_readme, load_trivia_data; from src.core.database import TriviaDatabase; db = TriviaDatabase(); leaderboard = db.get_leaderboard(); trivia_data = load_trivia_data(); update_readme(trivia_data, leaderboard)"
        
    - name: Print Top 10 Leaderboard
      env:
        TRIVIA_DB_PASSWORD: ${{ secrets.TRIVIA_DB_PASSWORD }}
      run: |
        echo "🔍 TOP 10 LEADERBOARD USERS:"
        python -c "from src.core.database import TriviaDatabase; from src.core.daily_trivia import get_top_leaderboard; db = TriviaDatabase(); leaderboard = db.get_leaderboard(); top_users = get_top_leaderboard(leaderboard, max_entries=10); print('No users in leaderboard.') if not top_users else [print(f'{i+1}. @{u}: {s[\"total_points\"]} points, {s[\"current_streak\"]} streak, {s[\"total_correct\"]} correct') for i, (u, s) in enumerate(top_users)]"
        echo "============================="
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git diff --quiet && git diff --staged --quiet || git commit -m "🤖 Daily update: Trivia + Daily fact + Database history - $(date +'%Y-%m-%d')"
        git push origin main 